name = "qliphoth-backend"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGIN = "https://qliphoth.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "qliphoth-db"
database_id = "f3c81138-4c36-4d85-97af-00d127a2f677"

[[durable_objects.bindings]]
name = "DEPARTMENT_ROOM"
class_name = "DepartmentRoom"

[[durable_objects.bindings]]
name = "RECEPTION_ROOM"
class_name = "ReceptionRoom"

[[durable_objects.bindings]]
name = "COMPETITIVE_ROOM"
class_name = "CompetitiveRoom"

[[durable_objects.bindings]]
name = "EXPLORATION_ROOM"
class_name = "ExplorationRoom"

[[durable_objects.bindings]]
name = "GLOBAL_CHAT"
class_name = "GlobalChat"

[[migrations]]
tag = "v1"
new_sqlite_classes = [
  "DepartmentRoom",
  "ReceptionRoom",
  "CompetitiveRoom",
  "ExplorationRoom",
]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["GlobalChat"]
